version: '3.4'

services:
  identitymanagementservice:
    image: ${DOCKER_REGISTRY-}identitymanagementservice
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Users=Host=postgres;Port=5432;Database=IdentityManagement;User Id=postgres;Password=IYmv5OcqEoANcO7s;
      - ConnectionStrings__Configuration=Host=postgres;Port=5432;Database=IdentityManagement;User Id=postgres;Password=IYmv5OcqEoANcO7s;
      - ConnectionStrings__Operational=Host=postgres;Port=5432;Database=IdentityManagement;User Id=postgres;Password=IYmv5OcqEoANcO7s;
      - ConnectionStrings__RabbitMQ=rabbitmq://rabbit:EvtNt7PKZqNNT06T@rabbitmq
      - Logs__Seq__BaseAddress=http://seq
      - ApiResource__ApiName=habitica-api
      - ApiResource__ApiSecret=43xoIIj2QFyvFNevScaPvOFUWNQa4unVwT75TOlG5cmwFyAwcI+BFW4mpkeN52jXSAHbUya58gCTkl5K/PNyaQ==
    networks:
      - lionize

networks:
      lionize:
        external:
          name: lionize