version: '3.4'

services:
  identitymanagementservice:
    image: ${DOCKER_REGISTRY-}identitymanagementservice
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Users=Server=mssql;Database=IdentityManagementService;User Id=sa;Password=z0aiDwJ0205q37Nr;
      - ConnectionStrings__Configuration=Server=mssql;Database=IdentityManagementService;User Id=sa;Password=z0aiDwJ0205q37Nr;
      - ConnectionStrings__Operational=Server=mssql;Database=IdentityManagementService;User Id=sa;Password=z0aiDwJ0205q37Nr;
      - ConnectionStrings__RabbitMQ=rabbitmq://rabbit:EvtNt7PKZqNNT06T@rabbitmq
      - ApiResource__ApiName=habitica-api
      - ApiResource__ApiSecret=43xoIIj2QFyvFNevScaPvOFUWNQa4unVwT75TOlG5cmwFyAwcI+BFW4mpkeN52jXSAHbUya58gCTkl5K/PNyaQ==
    networks:
      - lionize

networks:
      lionize:
        external:
          name: lionize